

export const CREATE_USER_REQUEST ="CREATE_USER_REQUEST"
export const CREATE_USER_SUCCESS ="CREATE_USER_SUCCESS"
export const CREATE_USER_ERROR ="CREATE_USER_ERROR"
export const CREATE_USER_RESET ="CREATE_USER_RESET"


export const GET_All_USER_REQUEST = "GET_ALL_USER_REQUEST"
export const GET_ALL_USER_SUCCESS= "GET_ALL_USER_SUCCESS"
export const GET_ALL_USER_ERROR= "GET_ALL_USER_ERROR"


export const GET_USER_REQUEST ="GET_USER_REQUEST"
export const GET_USER_SUCCESS ="GET_USER_SUCCESS"
export const GET_USER_ERROR ="GET_USER_ERROR"
export const GET_USER_RESET ="GET_USER_RESET"


export const DELETE_USER_REQUEST ="DELETE_USER_REQUEST"
export const DELETE_USER_SUCCESS ="DELETE_USER_SUCCESS"
export const DELETE_USER_ERROR ="DELETE_USER_ERROR"
export const DELETE_USER_RESET ="DELETE_USER_RESET"


export const UPDATE_USER_REQUEST ="UPDATE_USER_REQUEST"
export const UPDATE_USER_SUCCESS ="UPDATE_USER_SUCCESS"
export const UPDATE_USER_ERROR ="UPDATE_USER_ERROR"
export const UPDATE_USER_RESET ="UPDATE_USER_RESET"